-   repo: https://github.com/pre-commit/pre-commit
    sha: v0.9.4
    hooks:
    -   id: validate_config
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v0.6.1
    hooks:
    -   id: autopep8-wrapper
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: trailing-whitespace
-   repo: git@github.com:asottile/reorder_python_imports
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
-   repo: git@github.com:Lab41/verboten_words.git
    sha: v1.0.0
    hooks:
    -   id: verboten-words
