-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 96fb7fa10f2f4c11ed33482a9ad7474251e5e97f
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-case-conflict
    -   id: check-json
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: double-quote-string-fixer
    -   id: check-yaml
-   repo: git@github.com:asottile/reorder_python_imports
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
-   repo: git@github.com:Lab41/verboten_words.git
    sha: f07c2c0116d0bd6466dde6af4ef9bca5531d6cc7
    hooks:
    -   id: verboten-words
